apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - a02.yaml
patches:
  - target:
      kind: Application
      name: a02
    path: ../../../common/patches/argocd-app-settings.yaml