apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-prod"
resources:
  # - ../../../../../apps/gameservers/hytale/lobby/
  # - ../../../../../apps/gameservers/hytale/inventory-manager/
  # - ../../../../../apps/gameservers/hytale/adventure/
patches: []