apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - qu3.yaml
  - appproject.yaml
patches:
  - target:
      kind: Application
      name: qu3
    path: ../../../common/patches/argocd-app-settings.yaml