apiVersion: v1
kind: ConfigMap
metadata:
  name: before-starting-scripts
data:
  install-apps.sh: |
    #!/bin/sh
    echo "Installing Nextcloud apps..."
    # php /var/www/html/occ app:install contacts
    # php /var/www/html/occ app:install spreed
    # php /var/www/html/occ app:install collectives
    # php /var/www/html/occ app:install deck
    # php /var/www/html/occ app:install collectives
    # php /var/www/html/occ app:install passwords
    # php /var/www/html/occ app:install integration_openai
    # php /var/www/html/occ app:install assistant
    # php /var/www/html/occ app:install integration_github
    php /var/www/html/occ app:install announcementcenter
    php /var/www/html/occ app:install twofactor_totp
    echo "Nextcloud apps installation complete."