apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  namespace: "{{ .customer.name }}-open-webui"
spec:
  ingressClassName: "{{ .cluster.defaultIngressClass }}"
  rules:
    - host: ai.{{ .customer.primaryDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .customer.name }}-open-webui-{{ .customer.stage }}-server"
                port:
                  number: 80
  tls:
    - hosts:
      - ai.{{ .customer.primaryDomain }}
      secretName: open-webui-tls