image:
  # -- Open WebUI image tag (Open WebUI image tags can be found here: https://github.com/open-webui/open-webui)
  # @section -- Image configuration
  tag: "0.6.36"
sso:
  enabled: true
  mergeAccountsByEmail: true
  oidc:
    # -- Enable OIDC authentication
    # @section -- OIDC configuration
    enabled: true
    # -- OIDC client ID
    # @section -- OIDC configuration
    clientId: "{{ .ejson.openWebui.clientId }}"
    # -- OIDC client secret (ignored if clientExistingSecret is set)
    # @section -- OIDC configuration
    clientSecret: "{{ .ejson.openWebui.clientSecret }}"
    # -- OICD client secret from existing secret
    # @section -- OIDC configuration
    providerUrl: "{{ .ejson.openWebui.providerUrl }}"
    # -- Name of the provider to show on the UI
    # @section -- OIDC configuration
    providerName: "kubelize auth0"
    # -- Scopes to request (space-separated).
    # @section -- OIDC configuration
    scopes: "openid email profile"