apiVersion: v1
kind: Service
metadata:
  name: hytale-service
  namespace: b01-hytale
  labels:
    app: hytale-svc
spec:
  selector:
    app: hytale
  ports:
    - protocol: UDP
      port: 5520
      targetPort: 5520
  type: LoadBalancer  # Or LoadBalancer if you need external access.