apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-prod"
resources:
  - vanilla-minecraft-pvc.yaml
  - ../../../../../apps/filehosting/immich/
  - ../../../../../apps/gameservers/minecraft/vanilla/
  - ../../../../../apps/gameservers/tools/web-rcon/
  - ../../../../../apps/websites/open-webui/
  - ../../../../../apps/websites/linkstack/

patches:
- target:
    kind: Application
    name: vanilla-minecraft
  path: ../../../../../common/patches/argocd-app-settings.yaml
- target:
    kind: Application
    name: vanilla-minecraft
  path: patches/vanilla-minecraft.yaml
- target:
    kind: Application
    name: linkstack
  path: ../../../../../common/patches/argocd-app-settings.yaml
- target:
    kind: Application
    name: linkstack
  path: patches/linkstack.yaml