apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - t99.yaml
patches:
  - target:
      kind: Application
      name: t99
    path: ../../../common/patches/argocd-app-settings.yaml